import Head from "next/head";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="max-w-[600px] mx-auto flex flex-col h-5/6 justify-center items-center">
        <div className="my-20">
          <h1 className="font-bold text-3xl text-center">Welcome to</h1>
          <img src="/nextjs.png" alt="next js" className="my-10 w-[250px] mx-auto" />
          <h1 className="font-bold text-3xl text-center">News Application</h1>
        </div>
      </div>
    </div>
  );
}
