import Head from 'next/head'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[600px] mx-auto flex flex-col h-[100vh]">
        <NavBar/>
      </div>
    </div>
  )
}
